version: "3.7"
services:
  db:
    image: postgres:12.0-alpine
    env_file:
      - .env
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./postgres.conf:/usr/share/postgresql/postgresql.conf
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8089:8089"
    env_file:
      - .env
    depends_on:
      - db
