version: "3.7"
services:
  db:
    image: postgres:12.0-alpine
    ports:
      - 55432:5432
    env_file:
      - .env
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./postgres.conf:/usr/share/postgresql/postgresql.conf
    # networks:
    #   node_net:
    #     ipv4_address: 172.29.1.4
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - db
    # networks:
    #   node_net:
    #     ipv4_address: 172.29.1.3

# networks:
#   node_net:
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.29.0.0/16
